ttbz_vol:
  build: volume/
  volumes:
    - /var/lib/mysql
ttbz_db:
  build: database/
  volumes_from:
    - ttbz_vol
  environment:
    - MYSQL_ROOT_PASSWORD=rahasia
ttbz_app:
  build: app/
  links:
    - ttbz_db:mysql
  ports:
    - "80:80"
  environment:
    - TTBZ_APP_SERVER_NAME=bugzilla.touchten.com.dev
    - TTBZ_APP_SECRET_KEY=nKlQnwlIEMdjoRVwbMye3CHz5aUNO6wIGHwwSM9zOFZRa2vgRRTcbcAX9NwDlVSA
    - TTBZ_APP_SERVER_ADMIN=mario.stefano@ions.tech
    - TTBZ_APP_ADMIN_EMAIL=mario.stefano@ions.tech
    - TTBZ_APP_ADMIN_PASSWORD=rahasia
    - TTBZ_APP_ADMIN_REAL_NAME=Mario Stefano
